# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoria', '0005_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='filename',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=100),
        ),
    ]
