# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoria', '0007_auto_20170812_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
